services:
  - type: web
    name: ft-proxy-render
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FT_MODEL_ID
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false